Feat/fluent PoC
bcgov-nr/containers pull request #7
Opened 2021-11-24 16:43 UTC by ahbarnz-g

RHEL/FluentBit container - you can set the version via variable. Can't do that, if using https://github.com/fluent/fluent-bit-docker-image/blob/master/Dockerfile.x86_64. Also my RHEL/FB image currently is ~25 MB smaller (3/4 the size).

2021-11-24 17:19 UTC, DerekRoberts requested changes

2021-11-24 17:19 UTC, DerekRoberts commented on fluent-bit/Dockerfile
> +	make  > /dev/null && \
Remove `> /dev/null`

2021-11-24 17:19 UTC, DerekRoberts commented on fluent-bit/Dockerfile
> +COPY ./conf/ /usr/local/etc/fluent-bit/conf
Please use default locations.  `/fluent-bit/etc`

2021-11-24 17:19 UTC, DerekRoberts commented on fluent-bit/Dockerfile
> +        "-config=/usr/local/etc/fluent-bit/conf/fluent-bit.hcl", \
Please use default locations.  `/fluent-bit/etc`

2021-11-24 17:19 UTC, DerekRoberts commented on fluent-bit/Dockerfile
> +        "/usr/local/etc/fluent-bit/conf/fluent-bit.conf" \
Please use default locations.  `/fluent-bit/etc`

2021-11-24 17:19 UTC, DerekRoberts commented on fluent-bit/conf/filters.conf
> +    script /usr/local/etc/fluent-bit/conf/filters.lua
Please use default locations.  `/fluent-bit/etc`

2021-11-24 17:19 UTC, DerekRoberts commented on fluent-bit/conf/filters.conf
> +    script /usr/local/etc/fluent-bit/conf/filters.lua
Please use default locations.  `/fluent-bit/etc`

2021-11-24 17:19 UTC, DerekRoberts commented on fluent-bit/conf/fluent-bit-bulk.conf
> +    Parsers_File    /usr/local/etc/fluent-bit/conf/parsers.conf
Please use default locations.  `/fluent-bit/etc`

2021-11-24 17:19 UTC, DerekRoberts commented on fluent-bit/conf/fluent-bit.conf
> +    Parsers_File    /usr/local/etc/fluent-bit/conf/parsers.conf
Please use default locations.  `/fluent-bit/etc`

2021-11-24 17:19 UTC, DerekRoberts commented on fluent-bit/conf/metrics/filter/filters.conf
> +    script /usr/local/etc/fluent-bit/conf/filters.lua
Please use default locations.  `/fluent-bit/etc`

2021-11-24 17:19 UTC, DerekRoberts commented on fluent-bit/deploy.sh
> +# export FLUENT_LABEL_ENV="test"
Please remove the commented out line.

2021-11-24 17:19 UTC, DerekRoberts commented on fluent-bit/deploy.sh
> +export FLUENT_VERSION="1.8.7"
Shouldn't this be runtime configurable?

2021-11-24 17:19 UTC, DerekRoberts commented on fluent-bit/deploy.sh
> +export FLUENT_LABEL_ENV="local"
Shouldn't this be runtime configurable?

2021-11-24 17:19 UTC, DerekRoberts commented on fluent-bit/deploy.sh
> +# podman run --name fluent-bit --rm -e FLUENT_* -e AWS_* -e VAULT_* -e HOST_* --pid="host" -v "/proc/stat:/proc/stat:ro" --privileged "${IMAGE}"
Please remove commented code or turn them into notes.

2021-11-24 17:19 UTC, DerekRoberts commented on fluent-bit/deploy.sh
> +# podman run -i -t --rm --name fluent-bit -e "VAULT_*" -e "AWS_KINESIS_*" -e "FLUENT_*" -e "HOST_*" -v "$(pwd)/conf:/usr/local/etc/fluent-bit:z" --pid="host" -v "/proc/stat:/proc/stat:z" --privileged
Please remove commented code or turn them into notes.

2021-11-24 17:19 UTC, DerekRoberts commented on fluent-bit/Dockerfile
> +RUN curl -L -s ${fbURL} | tar xzv -C . --strip-components 1 && \
Since this could be used as a generator for multiple releases, please use GitHub as a source.
https://github.com/fluent/fluent-bit/releases

2021-11-24 18:18 UTC, ahbarnz-g commented on fluent-bit/Dockerfile
> +RUN curl -L -s ${fbURL} | tar xzv -C . --strip-components 1 && \
The FluentBit URL is github; did you mean to reference Bison?  I couldn't find Bison on GitHub, nothing I trusted anyway.

2021-11-24 19:20 UTC, DerekRoberts commented on fluent-bit/Dockerfile
> +RUN curl -L -s ${fbURL} | tar xzv -C . --strip-components 1 && \
No, that's Fluent's repo.  It's a good source.

2021-11-25 20:52 UTC, DerekRoberts approved these changes

2021-11-25 21:49 UTC, DerekRoberts approved these changes

2021-11-25 22:04 UTC, DerekRoberts approved these changes

2021-11-25 22:05 UTC, merged